name: Code Linting

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - "admin/**"
      - "docker/**"
      - "plugins/**"
      - "images/**"
      - "system/**"
      - "templates/**"
      - "tools/**"
      - "xml/**"
  push:
    branches:
      - master
      - develop
    paths:
      - "admin/**"
      - "docker/**"
      - "plugins/**"
      - "images/**"
      - "system/**"
      - "templates/**"
      - "tools/**"
      - "xml/**"

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: overtrue/phplint@3.4.0
        with:
          path: .
          options: --exclude="system/libs/polyfill-mbstring/bootstrap80.php"
