name: Code Testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - "admin/**"
      - "docker/**"
      - "plugins/**"
      - "images/**"
      - "system/**"
      - "templates/**"
      - "tools/**"
      - "xml/**"
  push:
    branches:
      - master
      - develop
    paths:
      - "admin/**"
      - "docker/**"
      - "plugins/**"
      - "images/**"
      - "system/**"
      - "templates/**"
      - "tools/**"
      - "xml/**"

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@main

      # todo: doesn't look like existing canary or tfs use lua testing yet
      # consider testing on new modules instead
      - name: Php tests
        run: true
